//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class mApplications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mApplications()
        {
            this.mAccessLog = new HashSet<mAccessLog>();
            this.mOperations = new HashSet<mOperations>();
            this.mProfiles = new HashSet<mProfiles>();
        }
    
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Origin { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public bool IsReadOnly { get; set; }
        public bool ManagesDelagations { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mAccessLog> mAccessLog { get; set; }
        public virtual mStatus mStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mOperations> mOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mProfiles> mProfiles { get; set; }
    }
}
