//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPrecioPorProducto
    {
        public int IdProducto { get; set; }
        public int IdTipoPrecio { get; set; }
        public decimal Precio { get; set; }
        public bool SeUsa { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual TipoPrecio TipoPrecio { get; set; }
    }
}
