//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientesSUPERTICKET
    {
        public string idinterno { get; set; }
        public int idreg { get; set; }
        public string usado { get; set; }
        public Nullable<System.DateTime> fechamod { get; set; }
        public string clave_usuario { get; set; }
        public string clave_sucursal { get; set; }
        public string clave { get; set; }
        public string nombre { get; set; }
        public string paterno { get; set; }
        public string comercial { get; set; }
        public string direccion { get; set; }
        public string numext { get; set; }
        public string numint { get; set; }
        public string ubicacion { get; set; }
        public string colonia { get; set; }
        public string delegacion { get; set; }
        public string poblacion { get; set; }
        public string entfed { get; set; }
        public string pais { get; set; }
        public string cp { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string rfc { get; set; }
        public string curp { get; set; }
        public string web { get; set; }
        public string email { get; set; }
        public string observacion { get; set; }
        public Nullable<decimal> diascred { get; set; }
        public Nullable<decimal> p_descuento1 { get; set; }
        public Nullable<decimal> p_descuento2 { get; set; }
        public Nullable<decimal> p_descuento3 { get; set; }
        public Nullable<decimal> limitecredito { get; set; }
        public Nullable<decimal> p_interes { get; set; }
        public Nullable<decimal> bloquear { get; set; }
        public string idtipocliente { get; set; }
        public string idzona { get; set; }
        public string diarevision { get; set; }
        public string horarevision { get; set; }
        public string diapagos { get; set; }
        public string horapagos { get; set; }
        public string idlistaprecio { get; set; }
        public string idpersonal { get; set; }
        public string Banco { get; set; }
        public string Cuenta_Banco { get; set; }
        public string clabe_banco { get; set; }
        public string claverelacionada { get; set; }
        public string subcuenta { get; set; }
        public string foto { get; set; }
        public string firma { get; set; }
        public Nullable<decimal> saldo_cxc { get; set; }
        public Nullable<decimal> Ventas { get; set; }
        public Nullable<System.DateTime> f_ult_venta { get; set; }
        public Nullable<System.DateTime> f_alta { get; set; }
        public Nullable<decimal> puntos { get; set; }
        public string cumpleanos { get; set; }
        public Nullable<decimal> campo_n_1 { get; set; }
        public Nullable<decimal> campo_n_2 { get; set; }
        public Nullable<decimal> campo_n_3 { get; set; }
        public string campo_t_1 { get; set; }
        public string campo_t_2 { get; set; }
        public string campo_t_3 { get; set; }
        public Nullable<decimal> CANCELADO { get; set; }
        public string metodo_pago { get; set; }
        public string idFormaPago { get; set; }
        public Nullable<decimal> Limite_Venta { get; set; }
    }
}
