//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraDetalle
    {
        public int IdCompraDetalle { get; set; }
        public int IdCompra { get; set; }
        public int IdProducto { get; set; }
        public short IdPresentacion { get; set; }
        public int Cantidad { get; set; }
        public decimal CostoUnitario { get; set; }
        public decimal CostoTotal { get; set; }
        public int Existencia { get; set; }
        public int CantidadVendida { get; set; }
        public Nullable<System.DateTime> FechaUltimoVendido { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Presentacion Presentacion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
