//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorteX
    {
        public int IdCorteX { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdVentaInicio { get; set; }
        public int IdVentaFin { get; set; }
        public decimal MontoVenta { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Venta Venta { get; set; }
        public virtual Venta Venta1 { get; set; }
    }
}
