//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devolucion()
        {
            this.DevolucionDetalle = new HashSet<DevolucionDetalle>();
        }
    
        public long IdDevolucion { get; set; }
        public System.DateTime FechaDevolucion { get; set; }
        public long FolioDevolucion { get; set; }
        public int IdOperador { get; set; }
        public int IdVenta { get; set; }
        public decimal ImporteDevolucion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Venta Venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionDetalle> DevolucionDetalle { get; set; }
    }
}
