//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_general
    {
        public string idinterno { get; set; }
        public int idreg { get; set; }
        public string usado { get; set; }
        public Nullable<System.DateTime> fechamod { get; set; }
        public string clave_usuario { get; set; }
        public string clave_sucursal { get; set; }
        public string iddocorigen { get; set; }
        public string iddocdestino { get; set; }
        public string clase { get; set; }
        public string tipodocto { get; set; }
        public Nullable<int> FOLIO { get; set; }
        public string serie { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public Nullable<System.DateTime> f_vencimiento { get; set; }
        public string idterminal { get; set; }
        public string sucursal { get; set; }
        public string idcortecaja { get; set; }
        public string turno { get; set; }
        public string idvendedor { get; set; }
        public string idcliente { get; set; }
        public string idproveedor { get; set; }
        public string doctoproveedor { get; set; }
        public Nullable<System.DateTime> fechadocto { get; set; }
        public string idconceptodocto { get; set; }
        public Nullable<decimal> peso { get; set; }
        public string idmoneda { get; set; }
        public string clavemoneda { get; set; }
        public Nullable<decimal> cotizacion { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> p_descto1 { get; set; }
        public Nullable<decimal> p_descto2 { get; set; }
        public Nullable<decimal> p_descto3 { get; set; }
        public Nullable<decimal> descuento1 { get; set; }
        public Nullable<decimal> descuento2 { get; set; }
        public Nullable<decimal> descuento3 { get; set; }
        public Nullable<decimal> ieps { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> iva11 { get; set; }
        public Nullable<decimal> iva16 { get; set; }
        public Nullable<decimal> impuesto2 { get; set; }
        public Nullable<decimal> retencion { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> PUNTOS { get; set; }
        public Nullable<decimal> ahorro { get; set; }
        public Nullable<decimal> impreso { get; set; }
        public Nullable<decimal> diasvigente { get; set; }
        public Nullable<decimal> valorpagado { get; set; }
        public Nullable<decimal> valorporcobrar { get; set; }
        public Nullable<decimal> AFECTADO { get; set; }
        public string IDALMACEN { get; set; }
        public string idFactGlobal { get; set; }
        public string observacion { get; set; }
        public Nullable<decimal> iva_incluido { get; set; }
        public string idE_Cert { get; set; }
        public string idE_Folio { get; set; }
        public Nullable<decimal> cfd_generado { get; set; }
        public Nullable<decimal> reporte_sat { get; set; }
        public Nullable<decimal> reporte_sat_canc { get; set; }
        public string archivo_xml { get; set; }
        public string poliza { get; set; }
        public Nullable<decimal> cancelado { get; set; }
        public Nullable<decimal> TotalSinDesc { get; set; }
        public Nullable<decimal> CambioCliente { get; set; }
        public Nullable<decimal> SumaPagos { get; set; }
        public Nullable<decimal> DescuentoConIva { get; set; }
        public Nullable<int> folio_cfdi { get; set; }
        public string uuid { get; set; }
        public string cbb { get; set; }
        public Nullable<System.DateTime> fechatimbrado { get; set; }
        public string certificado { get; set; }
        public string idrecibe { get; set; }
        public Nullable<decimal> IMPORTAR { get; set; }
        public string idClieSuc { get; set; }
        public Nullable<decimal> CanceladoEnSat { get; set; }
        public Nullable<decimal> RetencionIEPS { get; set; }
        public Nullable<decimal> ISH { get; set; }
        public Nullable<decimal> Retencion5Millar { get; set; }
        public Nullable<decimal> ImpresoOriginal { get; set; }
        public Nullable<decimal> ComisionPagada { get; set; }
        public Nullable<decimal> ComisionLiquidada { get; set; }
        public Nullable<int> partidas { get; set; }
        public Nullable<decimal> p_ieps { get; set; }
    }
}
