//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_detalle
    {
        public string idinterno { get; set; }
        public int idreg { get; set; }
        public Nullable<System.DateTime> fechamod { get; set; }
        public string clave_usuario { get; set; }
        public string clave_sucursal { get; set; }
        public string tipodocto { get; set; }
        public Nullable<int> folio { get; set; }
        public string iddocgeneral { get; set; }
        public string claveartic { get; set; }
        public string idarticulo { get; set; }
        public string idsecundaria { get; set; }
        public Nullable<decimal> multiplicador { get; set; }
        public string clase { get; set; }
        public Nullable<decimal> AfectaPedido { get; set; }
        public string descripcion { get; set; }
        public string presentacion { get; set; }
        public Nullable<decimal> id_presentacion { get; set; }
        public Nullable<decimal> factorconversion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> Existencia { get; set; }
        public Nullable<decimal> cant_fisico { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> precioneto { get; set; }
        public Nullable<decimal> ImporteNeto { get; set; }
        public Nullable<decimal> p_descuento { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> precio_cat { get; set; }
        public Nullable<decimal> puntos { get; set; }
        public string idlistaprecio { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> p_ieps { get; set; }
        public Nullable<decimal> p_iva { get; set; }
        public Nullable<decimal> p_impuesto2 { get; set; }
        public string idmoneda { get; set; }
        public Nullable<decimal> cotizacion { get; set; }
        public string idoferta { get; set; }
        public string idkit { get; set; }
        public string idalmacen { get; set; }
        public string idalmacen_entra { get; set; }
        public string idaduana { get; set; }
        public string idlote { get; set; }
        public Nullable<int> secuencia { get; set; }
        public string foto { get; set; }
        public Nullable<decimal> cancelado { get; set; }
        public Nullable<decimal> servicio { get; set; }
        public Nullable<int> partida { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<decimal> p_max_descto { get; set; }
        public string mensaje_oferta { get; set; }
        public Nullable<decimal> kit { get; set; }
        public Nullable<decimal> p_ish { get; set; }
        public Nullable<decimal> ImporteSinImpuesto { get; set; }
    }
}
