//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class formas_pago
    {
        public string idinterno { get; set; }
        public int idreg { get; set; }
        public Nullable<System.DateTime> fechamod { get; set; }
        public string clave_usuario { get; set; }
        public string clave_sucursal { get; set; }
        public string clave { get; set; }
        public string descripcion { get; set; }
        public string idmoneda { get; set; }
        public Nullable<decimal> tipo { get; set; }
        public string foto { get; set; }
        public Nullable<decimal> abrir_cajon { get; set; }
        public string ayuda { get; set; }
        public Nullable<decimal> secuencia { get; set; }
    }
}
