//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastos
    {
        public int IdGasto { get; set; }
        public byte IdTipoGasto { get; set; }
        public string Descripcion { get; set; }
        public decimal Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual TipoGasto TipoGasto { get; set; }
    }
}
