//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioHistorial
    {
        public long IdHistorial { get; set; }
        public Nullable<short> IdAlmacenOrigen { get; set; }
        public Nullable<short> IdAlmacenDestino { get; set; }
        public int IdProducto { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observaciones { get; set; }
        public int IdOperador { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Almacen Almacen1 { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
