//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int IdLog { get; set; }
        public int IdOperacion { get; set; }
        public int IdUsuario { get; set; }
        public int IdObject { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Operations Operations { get; set; }
    }
}
