//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosCompras
    {
        public int IdPagoCompra { get; set; }
        public int IdCompra { get; set; }
        public decimal ImportePago { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string Observaciones { get; set; }
        public Nullable<short> IdFormaDePago { get; set; }
        public int IdUsuario { get; set; }
        public byte IdEstatus { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Estatus Estatus { get; set; }
        public virtual FormaDePago FormaDePago { get; set; }
    }
}
