//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public string idinterno { get; set; }
        public int idreg { get; set; }
        public string usado { get; set; }
        public Nullable<System.DateTime> fechamod { get; set; }
        public string clave_usuario { get; set; }
        public string clave_sucursal { get; set; }
        public string clave { get; set; }
        public string contrasena { get; set; }
        public Nullable<decimal> delegar { get; set; }
        public string perfil { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string cp { get; set; }
        public string sector { get; set; }
        public string colonia { get; set; }
        public string poblacion { get; set; }
        public string entfed { get; set; }
        public string pais { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string rfc { get; set; }
        public string curp { get; set; }
        public string imss { get; set; }
        public Nullable<System.DateTime> f_nacimiento { get; set; }
        public string clavenomina { get; set; }
        public Nullable<System.DateTime> f_alta { get; set; }
        public string banco { get; set; }
        public string cuentabanco { get; set; }
        public string clabe { get; set; }
        public Nullable<System.DateTime> f_baja { get; set; }
        public Nullable<System.DateTime> f_antiguedad { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        public Nullable<decimal> p_comision { get; set; }
        public string puesto { get; set; }
        public string claveacceso { get; set; }
        public string idnivelacceso { get; set; }
        public string Nacionalidad { get; set; }
        public string Documentacion { get; set; }
        public string foto { get; set; }
        public string nota { get; set; }
        public string subcuenta { get; set; }
        public Nullable<decimal> cancelado { get; set; }
        public string email { get; set; }
        public Nullable<decimal> Venta_minima { get; set; }
    }
}
