//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.CompraDetalle = new HashSet<CompraDetalle>();
            this.TipoPrecioPorProducto = new HashSet<TipoPrecioPorProducto>();
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public int IdProducto { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public long Cantidad { get; set; }
        public int IdTipoProducto { get; set; }
        public int IdSubTipoProducto { get; set; }
        public int IdMarca { get; set; }
        public int IdProveedor { get; set; }
        public int IdTalla { get; set; }
        public int IdUnidad { get; set; }
        public int IdGenero { get; set; }
        public byte[] Imagen { get; set; }
        public decimal PrecioVenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompraDetalle> CompraDetalle { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual SubTipoProducto SubTipoProducto { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
        public virtual Unidad Unidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoPrecioPorProducto> TipoPrecioPorProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
