//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SUPERTICKETEntities : DbContext
    {
        public SUPERTICKETEntities()
            : base("name=SUPERTICKETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doc_detalle> doc_detalle { get; set; }
        public virtual DbSet<doc_general> doc_general { get; set; }
        public virtual DbSet<doc_pagos> doc_pagos { get; set; }
        public virtual DbSet<clientesSUPERTICKET> clientesSUPERTICKET { get; set; }
        public virtual DbSet<personal> personal { get; set; }
        public virtual DbSet<formas_pago> formas_pago { get; set; }
    }
}
