//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPrecioPorProducto
    {
        public int IdProducto { get; set; }
        public int IdTipoPrecio { get; set; }
        public decimal Precio { get; set; }
        public bool SeUsa { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual TipoPrecio TipoPrecio { get; set; }
    }
}
