//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogManagement.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaDetalle
    {
        public int IdVentaDetalle { get; set; }
        public int IdVenta { get; set; }
        public int IdProducto { get; set; }
        public short IdPresentacion { get; set; }
        public short IdTipoPrecio { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal PrecioTotal { get; set; }
        public decimal Descuento { get; set; }
        public decimal CostoUnitario { get; set; }
    
        public virtual Presentacion Presentacion { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual TipoPrecio TipoPrecio { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
