CREATE TABLE [dbo].[Estatus](
	[IdEstatus] TINYINT IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](50) NOT NULL
 CONSTRAINT [PK_mEstatus] PRIMARY KEY CLUSTERED 
(
	[IdEstatus] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
